### PR TITLE
Support symlinks for init scripts

### PR DESCRIPTION
**Pull request by dzeban**
**Description of the change**

Allow symlinks for init scripts in addition to regular files.

**Benefits**

This will allow using existing migration scripts that can be symlinked in the directory to be mounted inside this image.

### CODE REVIEW

**Review by marcosbc — CHANGES_REQUESTED** [review]
Thanks for the contribution!

It is my understanding that this would cause any file to be matched, in addition to symlinks matching the regexp, i.e.:

* Any file
* Any symlink that match .sh/.cql/.cql.gz

To fix this, you could group the "or" condition:

```
find \( -type f -o -type l \) -regex '.*\.\(sh\|cql\|cql.gz\)'
```

**Comment by dzeban** [comment]
> Thanks for the contribution!
> 
> It is my understanding that this would cause an unwanted effect, i.e. returning:
> 
> * Any file
> * Any symlink that match .sh/.cql/.cql.gz
> 
> To fix this, you could group the "or" condition:
> 
> ```
> find \( -type f -o -type l \) -regex '.*\.\(sh\|cql\|cql.gz\)'
> ```

Thanks for the review. You are right, `find` will return any file. I've fixed the condition.

**Review by marcosbc — APPROVED** [review]
LGTM, thanks for the contribution! We'll working on releasing a new Bitnami Docker image for Cassandra which may take a few hours, at latest it should be available tomorrow morning.

**Comment by marcosbc** [comment]
Hi @dzeban, just wanted to let you know that Cassandra `3.11.9-debian-10-r52` was released with this fix.

**Comment by dzeban** [comment]
Thanks a lot!

**Pull request merged**
